### ISSUE TITLE
Print to stderr?

### ISSUE THREAD

**Issue by besfahbod** [tylerwince/pydbg#11]
How about we print to `stderr` by default, instead of print, similar to [Rust's `std::dbg`](https://doc.rust-lang.org/std/macro.dbg.html)?

https://github.com/tylerwince/pydbg/blob/4d787cd565b8a6eddc2ad27eaee6abc3f8d42959/pydbg.py#L30-L32

We can have some optional kwarg to enable printing to `stdout`, if you think it's really needed.

**Comment by tylerwince** [comment]
Rust's `std::dbg` actually uses both `stdout` and `stderr` based on the datatype of the variable. I was looking at Python 3.8 typed_ast and potentially using that if users have 3.8 or determining if the type is an `Exception` to use stderr if it's an exception, otherwise stdout. 

I haven't had time to implement, but would welcome a PR if you want to take a stab

**Comment by tylerwince** [comment]
Dang - totally misread the initial blog post on `std::dbg`. You are right that it prints to `stderr` only. I read it as "errors print to stderr and values print to stdout". 

We don't have to be an exact copy of the dbg macro. Maybe we default to `stderr` and allow an extra param passed that could print to `stdout` if the user asks for it
